### ISSUE TITLE
Create a basic tree of repository 

### ISSUE THREAD

**Issue by ryukinix** [DestructHub/sotn-reborn#2]
We need a idiomatic structure of a Rust repository. Any good ideas?

**Comment by ryukinix** [comment]
I think this was already done in the last commits. We can close this issue, @PedroHLC? (LHC?)

**Comment by ryukinix** [comment]
@ryukinix I'm lain. Not really I am what I am.

**Comment by PedroHLC** [comment]
@ryukinix close #2
